[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run dev --workspace=server"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[nixpacks]
buildCommand = "npm install --workspaces=false"

